// TG5 session template — 43 teaching days, 9 periods per day
// Air Days: enter as negated days when creating a plan
// isPEd:true = muted brown  |  isNonMathsExam:true = muted red
const TG5_TEMPLATE = [
  // ── Day 1 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Intro to APO", "isMaths": false},
    {"slot": "p2", "label": "Intro to APO", "isMaths": false},
    {"slot": "p3", "isMaths": true, "section": "pt1", "pEnd": 1, "label": "Maths pt1"},
    {"slot": "p4", "isMaths": true, "section": "pt1", "pEnd": 2, "label": "Maths pt1"},
    {"slot": "p6", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p7", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p8", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p9", "label": "Eng Drawing", "isMaths": false},
  ],
  // ── Day 2 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt1", "pEnd": 3, "label": "Maths pt1"},
    {"slot": "p2", "isMaths": true, "section": "pt1", "pEnd": 4, "label": "Maths pt1"},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p6", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p7", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p8", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p9", "label": "Eng Drawing", "isMaths": false},
  ],
  // ── Day 3 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Beliefs & Values", "isMaths": false},
    {"slot": "p2", "label": "Beliefs & Values", "isMaths": false},
    {"slot": "p3", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p4", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p6", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p7", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p8", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p9", "label": "Eng Drawing", "isMaths": false},
  ],
  // ── Day 4 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p2", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p3", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p4", "label": "Eng Drawing", "isMaths": false},
    {"slot": "p6", "label": "P'Ed Cancelled", "isMaths": false, "isPEd": true},
    {"slot": "p7", "label": "P'Ed Cancelled", "isMaths": false, "isPEd": true},
    {"slot": "p8", "label": "Eng Drawing / Courageous Conv.", "isMaths": false},
    {"slot": "p9", "label": "Eng Drawing / Courageous Conv.", "isMaths": false},
  ],
  // ── Day 5 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p2", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p3", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p4", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p6", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p7", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p8", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p9", "label": "Eng Drawing Exam", "isMaths": false, "isNonMathsExam": true},
  ],
  // ── Day 6 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt1", "pEnd": 5, "label": "Maths pt1"},
    {"slot": "p2", "isMaths": true, "section": "pt1", "pEnd": 6, "label": "Maths pt1"},
    {"slot": "p3", "isMaths": true, "section": "pt1", "pEnd": 7, "label": "Maths pt1"},
    {"slot": "p4", "isMaths": true, "section": "pt1", "pEnd": 8, "label": "Maths pt1"},
    {"slot": "p6", "isMaths": true, "section": "pt1", "pEnd": 9, "label": "Maths pt1"},
    {"slot": "p7", "isMaths": true, "section": "pt1", "pEnd": 10, "label": "Maths pt1"},
    {"slot": "p8", "isMaths": true, "section": "pt1", "pEnd": 11, "label": "Maths pt1"},
    {"slot": "p9", "isMaths": true, "section": "pt1", "pEnd": 12, "label": "Maths pt1"},
  ],
  // ── Day 7 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt1", "pEnd": 13, "label": "Maths pt1"},
    {"slot": "p2", "isMaths": true, "section": "pt1", "pEnd": 14, "label": "Maths pt1"},
    {"slot": "p3", "isMaths": true, "section": "pt1", "pEnd": 15, "label": "Maths pt1"},
    {"slot": "p4", "isMaths": true, "section": "pt1", "pEnd": 16, "label": "Maths pt1"},
    {"slot": "p6", "isMaths": true, "section": "pt1", "pEnd": 17, "label": "Maths pt1"},
    {"slot": "p7", "isMaths": true, "section": "pt1", "pEnd": 18, "label": "Maths pt1"},
    {"slot": "p8", "isMaths": true, "section": "pt1", "pEnd": 19, "label": "Maths pt1"},
    {"slot": "p9", "isMaths": true, "section": "pt1", "pEnd": 20, "label": "Maths pt1"},
  ],
  // ── Day 8 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt1", "pEnd": 21, "label": "Maths pt1"},
    {"slot": "p2", "isMaths": true, "section": "pt1", "pEnd": 22, "label": "Maths pt1"},
    {"slot": "p3", "isMaths": true, "section": "pt1", "pEnd": 23, "label": "Maths pt1"},
    {"slot": "p4", "isMaths": true, "section": "pt1", "pEnd": 24, "label": "Maths pt1"},
    {"slot": "p6", "label": "CAD", "isMaths": false},
    {"slot": "p7", "label": "CAD", "isMaths": false},
    {"slot": "p8", "label": "CAD", "isMaths": false},
    {"slot": "p9", "label": "CAD", "isMaths": false},
  ],
  // ── Day 9 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "CAD", "isMaths": false},
    {"slot": "p2", "label": "CAD", "isMaths": false},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p6", "isMaths": true, "section": "pt1", "pEnd": 25, "label": "Maths pt1"},
    {"slot": "p7", "isMaths": true, "section": "pt1", "pEnd": 26, "label": "Maths pt1"},
    {"slot": "p8", "isMaths": true, "section": "pt1", "pEnd": 27, "label": "Maths pt1"},
    {"slot": "p9", "isMaths": true, "section": "pt1", "pEnd": 28, "label": "Maths pt1"},
  ],
  // ── Day 10 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt1", "pEnd": 29, "label": "Maths pt1", "isExam": true},
    {"slot": "p2", "isMaths": true, "section": "pt1", "pEnd": 30, "label": "Maths pt1", "isExam": true},
    {"slot": "p3", "label": "CAD", "isMaths": false},
    {"slot": "p4", "label": "CAD", "isMaths": false},
    {"slot": "p5", "label": "PowerBI — Eng Drawing & CAD", "isMaths": false},
    {"slot": "p6", "label": "CAD", "isMaths": false},
    {"slot": "p7", "label": "CAD", "isMaths": false},
    {"slot": "p8", "label": "CAD", "isMaths": false},
    {"slot": "p9", "label": "CAD Exam", "isMaths": false, "isNonMathsExam": true},
  ],
  // ── Day 11 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "CAD Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p2", "label": "CAD Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p3", "label": "CAD Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p4", "label": "CAD Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p6", "isMaths": true, "section": "pt2a", "pEnd": 1, "label": "Maths pt2a"},
    {"slot": "p7", "isMaths": true, "section": "pt2a", "pEnd": 2, "label": "Maths pt2a"},
    {"slot": "p8", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p9", "label": "P'Ed", "isMaths": false, "isPEd": true},
  ],
  // ── Day 12 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 3, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 4, "label": "Maths pt2a"},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p5", "label": "F2F — Eng Drawing & CAD", "isMaths": false},
    {"slot": "p6", "label": "Tech HS", "isMaths": false},
    {"slot": "p7", "label": "Tech HS", "isMaths": false},
    {"slot": "p8", "label": "Tech HS", "isMaths": false},
    {"slot": "p9", "label": "Tech HS", "isMaths": false},
  ],
  // ── Day 13 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 5, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 6, "label": "Maths pt2a"},
    {"slot": "p3", "isMaths": true, "section": "pt2a", "pEnd": 7, "label": "Maths pt2a"},
    {"slot": "p4", "isMaths": true, "section": "pt2a", "pEnd": 8, "label": "Maths pt2a"},
    {"slot": "p6", "label": "Tech HS", "isMaths": false},
    {"slot": "p7", "label": "Tech HS", "isMaths": false},
    {"slot": "p8", "label": "Tech HS", "isMaths": false},
    {"slot": "p9", "label": "Tech HS", "isMaths": false},
  ],
  // ── Day 14 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 9, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 10, "label": "Maths pt2a"},
    {"slot": "p3", "isMaths": true, "section": "pt2a", "pEnd": 11, "label": "Maths pt2a"},
    {"slot": "p4", "isMaths": true, "section": "pt2a", "pEnd": 12, "label": "Maths pt2a"},
    {"slot": "p6", "label": "Tech HS", "isMaths": false},
    {"slot": "p7", "label": "Tech HS", "isMaths": false},
    {"slot": "p8", "label": "Tech HS", "isMaths": false},
    {"slot": "p9", "label": "Tech HS", "isMaths": false},
  ],
  // ── Day 15 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 13, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 14, "label": "Maths pt2a"},
    {"slot": "p3", "label": "Beliefs & Values", "isMaths": false},
    {"slot": "p4", "label": "Beliefs & Values", "isMaths": false},
    {"slot": "p6", "label": "Tech HS", "isMaths": false},
    {"slot": "p7", "label": "Tech HS", "isMaths": false},
    {"slot": "p8", "label": "Tech HS", "isMaths": false},
    {"slot": "p9", "label": "Tech HS", "isMaths": false},
  ],
  // ── Day 16 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Tech HS", "isMaths": false},
    {"slot": "p2", "label": "Tech HS", "isMaths": false},
    {"slot": "p3", "label": "Tech HS", "isMaths": false},
    {"slot": "p4", "label": "Tech HS", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2a", "pEnd": 15, "label": "Maths pt2a"},
    {"slot": "p7", "isMaths": true, "section": "pt2a", "pEnd": 16, "label": "Maths pt2a"},
    {"slot": "p8", "isMaths": true, "section": "pt2a", "pEnd": 17, "label": "Maths pt2a"},
    {"slot": "p9", "isMaths": true, "section": "pt2a", "pEnd": 18, "label": "Maths pt2a"},
  ],
  // ── Day 17 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Tech HS", "isMaths": false},
    {"slot": "p2", "label": "Tech HS", "isMaths": false},
    {"slot": "p3", "label": "Tech HS", "isMaths": false},
    {"slot": "p4", "label": "Tech HS", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2a", "pEnd": 19, "label": "Maths pt2a"},
    {"slot": "p7", "isMaths": true, "section": "pt2a", "pEnd": 20, "label": "Maths pt2a"},
    {"slot": "p8", "isMaths": true, "section": "pt2a", "pEnd": 21, "label": "Maths pt2a"},
    {"slot": "p9", "isMaths": true, "section": "pt2a", "pEnd": 22, "label": "Maths pt2a"},
  ],
  // ── Day 18 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Courageous Conv. / Tech HS", "isMaths": false},
    {"slot": "p2", "label": "Tech HS", "isMaths": false},
    {"slot": "p3", "label": "Tech HS", "isMaths": false},
    {"slot": "p4", "label": "Tech HS", "isMaths": false},
    {"slot": "p5", "label": "PowerBI — Tech HS", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2a", "pEnd": 23, "label": "Maths pt2a"},
    {"slot": "p7", "isMaths": true, "section": "pt2a", "pEnd": 24, "label": "Maths pt2a"},
    {"slot": "p8", "isMaths": true, "section": "pt2a", "pEnd": 25, "label": "Maths pt2a"},
    {"slot": "p9", "isMaths": true, "section": "pt2a", "pEnd": 26, "label": "Maths pt2a"},
  ],
  // ── Day 19 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p2", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p3", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p4", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p6", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p7", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p8", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p9", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
  ],
  // ── Day 20 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p2", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p3", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p4", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p6", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p7", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p8", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p9", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
  ],
  // ── Day 21 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p2", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p3", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p4", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p6", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p7", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p8", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p9", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
  ],
  // ── Day 22 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p2", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p3", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p4", "label": "Tech HS Exam", "isMaths": false, "isNonMathsExam": true},
    {"slot": "p5", "label": "Log into MODnet", "isMaths": false},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 23 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 27, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 28, "label": "Maths pt2a"},
    {"slot": "p3", "isMaths": true, "section": "pt2a", "pEnd": 29, "label": "Maths pt2a"},
    {"slot": "p4", "isMaths": true, "section": "pt2a", "pEnd": 30, "label": "Maths pt2a"},
    {"slot": "p5", "label": "F2F — Tech HS", "isMaths": false},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 24 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 31, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 32, "label": "Maths pt2a"},
    {"slot": "p3", "label": "Beliefs & Values", "isMaths": false},
    {"slot": "p4", "label": "Beliefs & Values", "isMaths": false},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 25 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 33, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 34, "label": "Maths pt2a"},
    {"slot": "p3", "isMaths": true, "section": "pt2a", "pEnd": 35, "label": "Maths pt2a"},
    {"slot": "p4", "isMaths": true, "section": "pt2a", "pEnd": 36, "label": "Maths pt2a"},
    {"slot": "p6", "isMaths": true, "section": "pt2a", "pEnd": 37, "label": "Maths pt2a"},
    {"slot": "p7", "isMaths": true, "section": "pt2a", "pEnd": 38, "label": "Maths pt2a"},
    {"slot": "p8", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p9", "label": "P'Ed", "isMaths": false, "isPEd": true},
  ],
  // ── Day 26 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2a", "pEnd": 39, "label": "Maths pt2a"},
    {"slot": "p2", "isMaths": true, "section": "pt2a", "pEnd": 40, "label": "Maths pt2a"},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p6", "label": "TDC Admin", "isMaths": false},
    {"slot": "p7", "isMaths": true, "section": "pt2a", "pEnd": 41, "label": "Maths pt2a", "isExam": true},
    {"slot": "p8", "isMaths": true, "section": "pt2a", "pEnd": 42, "label": "Maths pt2a", "isExam": true},
    {"slot": "p9", "isMaths": true, "section": "pt2a", "pEnd": 43, "label": "Maths pt2a", "isExam": true},
  ],
  // ── Day 27 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "isMaths": true, "section": "pt2b", "pEnd": 1, "label": "Maths pt2b"},
    {"slot": "p9", "isMaths": true, "section": "pt2b", "pEnd": 2, "label": "Maths pt2b"},
  ],
  // ── Day 28 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2b", "pEnd": 3, "label": "Maths pt2b"},
    {"slot": "p7", "isMaths": true, "section": "pt2b", "pEnd": 4, "label": "Maths pt2b"},
    {"slot": "p8", "isMaths": true, "section": "pt2b", "pEnd": 5, "label": "Maths pt2b"},
    {"slot": "p9", "isMaths": true, "section": "pt2b", "pEnd": 6, "label": "Maths pt2b"},
  ],
  // ── Day 29 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p6", "isMaths": true, "section": "pt2b", "pEnd": 7, "label": "Maths pt2b"},
    {"slot": "p7", "isMaths": true, "section": "pt2b", "pEnd": 8, "label": "Maths pt2b"},
    {"slot": "p8", "isMaths": true, "section": "pt2b", "pEnd": 9, "label": "Maths pt2b"},
    {"slot": "p9", "isMaths": true, "section": "pt2b", "pEnd": 10, "label": "Maths pt2b"},
  ],
  // ── Day 30 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2b", "pEnd": 11, "label": "Maths pt2b"},
    {"slot": "p7", "isMaths": true, "section": "pt2b", "pEnd": 12, "label": "Maths pt2b"},
    {"slot": "p8", "isMaths": true, "section": "pt2b", "pEnd": 13, "label": "Maths pt2b"},
    {"slot": "p9", "isMaths": true, "section": "pt2b", "pEnd": 14, "label": "Maths pt2b"},
  ],
  // ── Day 31 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2b", "pEnd": 15, "label": "Maths pt2b"},
    {"slot": "p7", "isMaths": true, "section": "pt2b", "pEnd": 16, "label": "Maths pt2b"},
    {"slot": "p8", "isMaths": true, "section": "pt2b", "pEnd": 17, "label": "Maths pt2b"},
    {"slot": "p9", "isMaths": true, "section": "pt2b", "pEnd": 18, "label": "Maths pt2b"},
  ],
  // ── Day 32 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2b", "pEnd": 19, "label": "Maths pt2b"},
    {"slot": "p2", "isMaths": true, "section": "pt2b", "pEnd": 20, "label": "Maths pt2b"},
    {"slot": "p3", "isMaths": true, "section": "pt2b", "pEnd": 21, "label": "Maths pt2b"},
    {"slot": "p4", "isMaths": true, "section": "pt2b", "pEnd": 22, "label": "Maths pt2b"},
    {"slot": "p6", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p7", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 33 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2b", "pEnd": 23, "label": "Maths pt2b"},
    {"slot": "p2", "isMaths": true, "section": "pt2b", "pEnd": 24, "label": "Maths pt2b", "isExam": true},
    {"slot": "p3", "isMaths": true, "section": "pt2b", "pEnd": 25, "label": "Maths pt2b", "isExam": true},
    {"slot": "p4", "isMaths": true, "section": "pt2b", "pEnd": 26, "label": "Maths pt2b", "isExam": true},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 34 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2c", "pEnd": 1, "label": "Maths pt2c"},
    {"slot": "p2", "isMaths": true, "section": "pt2c", "pEnd": 2, "label": "Maths pt2c"},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 35 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2c", "pEnd": 3, "label": "Maths pt2c"},
    {"slot": "p2", "isMaths": true, "section": "pt2c", "pEnd": 4, "label": "Maths pt2c"},
    {"slot": "p3", "isMaths": true, "section": "pt2c", "pEnd": 5, "label": "Maths pt2c"},
    {"slot": "p4", "isMaths": true, "section": "pt2c", "pEnd": 6, "label": "Maths pt2c"},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 36 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2c", "pEnd": 7, "label": "Maths pt2c"},
    {"slot": "p2", "isMaths": true, "section": "pt2c", "pEnd": 8, "label": "Maths pt2c"},
    {"slot": "p3", "isMaths": true, "section": "pt2c", "pEnd": 9, "label": "Maths pt2c"},
    {"slot": "p4", "isMaths": true, "section": "pt2c", "pEnd": 10, "label": "Maths pt2c"},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 37 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2c", "pEnd": 11, "label": "Maths pt2c"},
    {"slot": "p2", "isMaths": true, "section": "pt2c", "pEnd": 12, "label": "Maths pt2c"},
    {"slot": "p3", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p4", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 38 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2c", "pEnd": 13, "label": "Maths pt2c"},
    {"slot": "p7", "isMaths": true, "section": "pt2c", "pEnd": 14, "label": "Maths pt2c"},
    {"slot": "p8", "isMaths": true, "section": "pt2c", "pEnd": 15, "label": "Maths pt2c"},
    {"slot": "p9", "isMaths": true, "section": "pt2c", "pEnd": 16, "label": "Maths pt2c"},
  ],
  // ── Day 39 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Courageous Conv.", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2c", "pEnd": 17, "label": "Maths pt2c"},
    {"slot": "p7", "isMaths": true, "section": "pt2c", "pEnd": 18, "label": "Maths pt2c"},
    {"slot": "p8", "isMaths": true, "section": "pt2c", "pEnd": 19, "label": "Maths pt2c"},
    {"slot": "p9", "isMaths": true, "section": "pt2c", "pEnd": 20, "label": "Maths pt2c"},
  ],
  // ── Day 40 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "TDC Admin", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p6", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p7", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p8", "isMaths": true, "section": "pt2c", "pEnd": 21, "label": "Maths pt2c"},
    {"slot": "p9", "isMaths": true, "section": "pt2c", "pEnd": 22, "label": "Maths pt2c"},
  ],
  // ── Day 41 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "Elec Science", "isMaths": false},
    {"slot": "p2", "label": "Elec Science", "isMaths": false},
    {"slot": "p3", "label": "Elec Science", "isMaths": false},
    {"slot": "p4", "label": "Elec Science", "isMaths": false},
    {"slot": "p5", "label": "Log into MODnet", "isMaths": false},
    {"slot": "p6", "isMaths": true, "section": "pt2c", "pEnd": 23, "label": "Maths pt2c"},
    {"slot": "p7", "isMaths": true, "section": "pt2c", "pEnd": 24, "label": "Maths pt2c"},
    {"slot": "p8", "isMaths": true, "section": "pt2c", "pEnd": 25, "label": "Maths pt2c"},
    {"slot": "p9", "isMaths": true, "section": "pt2c", "pEnd": 26, "label": "Maths pt2c"},
  ],
  // ── Day 42 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "isMaths": true, "section": "pt2c", "pEnd": 27, "label": "Maths pt2c"},
    {"slot": "p2", "isMaths": true, "section": "pt2c", "pEnd": 28, "label": "Maths pt2c"},
    {"slot": "p3", "isMaths": true, "section": "pt2c", "pEnd": 29, "label": "Maths pt2c"},
    {"slot": "p4", "isMaths": true, "section": "pt2c", "pEnd": 30, "label": "Maths pt2c"},
    {"slot": "p6", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p7", "label": "P'Ed", "isMaths": false, "isPEd": true},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ],
  // ── Day 43 ──────────────────────────────────────────────────
  [
    {"slot": "p1", "label": "TDC Admin", "isMaths": false},
    {"slot": "p2", "isMaths": true, "section": "pt2c", "pEnd": 31, "label": "Maths pt2c", "isExam": true},
    {"slot": "p3", "isMaths": true, "section": "pt2c", "pEnd": 32, "label": "Maths pt2c", "isExam": true},
    {"slot": "p4", "isMaths": true, "section": "pt2c", "pEnd": 33, "label": "Maths pt2c", "isExam": true},
    {"slot": "p6", "label": "Elec Science", "isMaths": false},
    {"slot": "p7", "label": "Elec Science", "isMaths": false},
    {"slot": "p8", "label": "Elec Science", "isMaths": false},
    {"slot": "p9", "label": "Elec Science", "isMaths": false},
  ]
];
